# Generated by Django 4.2.4 on 2023-10-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
